const images = {
    CUT: require('../assets/images/CUT.png'),
    bottom_image1: require('../assets/images/bottom-image1.png'),
    bottom_image: require('../assets/images/bottom-image.png'),
    bottom_image0: require('../assets/images/bottom-image0.png'),
    bottom_image2: require('../assets/images/bottom-image2.png'),
    bottom_image3: require('../assets/images/bottom-image3.png'),
    bottom_image4: require('../assets/images/bottom-image4.png'),
    back_red: require('../assets/images/right_arrow_red.png'),
    f_mark: require('../assets/images/facebook.png'),
    g_mark: require('../assets/images/google.png'),
    male: require('../assets/images/male.png'),
    female: require('../assets/images/female.png'),
    check: require('../assets/images/check.png'),
    location: require('../assets/images/location.png'),
    star: require('../assets/images/star.png'),
    info: require('../assets/images/info.png'),
    home: require('../assets/images/Home.png'),
    calendar: require('../assets/images/Calendar.png'),
    shop: require('../assets/images/Shop.png'),
    profile: require('../assets/images/Profile.png'),
    mask1: require('../assets/images/mask1.png'),
    mask2: require('../assets/images/mask2.png'),
    mask3: require('../assets/images/mask3.png'),
    circle_calendar: require('../assets/images/circle_calendar.png'),
    circle_setting: require('../assets/images/circle_setting.png'),
    circle_star: require('../assets/images/circle_star.png'),
    edit: require('../assets/images/edit.png'),
    pin: require('../assets/images/Pin.png'),
    cardmask: require('../assets/images/cardmask.png'),
    visa: require('../assets/images/visa.png'),
    visacheck: require('../assets/images/visacheck.png'),
    shopmain: require('../assets/images/shopmain.png'),
    search : require('../assets/images/search.png'),
    carticon : require('../assets/images/cart.png'),
    product :  require('../assets/images/product.png'),
    background : require('../assets/images/background.png'),
    arrow : require('../assets/images/Arrow.png'),
    close : require('../assets/images/close.png'),
    delete : require('../assets/images/close.png')
}

export default images;